version: "3.9"
services:
  eureka-server:
    container_name: eureka-server
    image: apolos7/eureka-server:latest
    ports:
      - "8761:8761"
    environment:
      PORT: 8761
    networks:
      - msvc
    restart: always

networks:
  msvc:
    name: msvc